services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8081
    dns:
      - 8.8.4.4
    networks:
      - little_farmer

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    ports:
      - "8081:8081"
    environment:
      - DEFAULT_ADMIN_USER=admin
      - DEFAULT_ADMIN_PASSWORD=admin # Change this in production
      - API_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/
      - OLLAMA_SERVER=http://ollama:11434/
    depends_on:
      - redis
      - mongo
    networks:
      - little_farmer

  ollama: # for AI
      image: ollama/ollama:latest
      ports:
        - "11434:11434"
      networks:
        - little_farmer
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all
      volumes:
        - ./ollama:/root/.ollama:rw

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - little_farmer

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - little_farmer

networks:
  little_farmer:
    driver: bridge