services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - taiwan_arrivals_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["python3", "./backend/startup.py"]
    ports:
      - "8081:8081"
    environment:
      - DEFAULT_ADMIN_USER="admin"
      - DEFAULT_ADMIN_PASSWORD="admin" # Change this in production
      - API_HOST="0.0.0.0"
      - REDIS_HOST="redis"
      - REDIS_PORT="6379"
      - MONGO_URI="mongodb://mongo:27017"
      - OLLAMA_SERVER="http://ollama:11434"
    depends_on:
      - redis
      - mongo
    networks:
      - little_farmer

  ollama: # for AI
      image: ollama/ollama:latest
      ports:
        - "11434:11434"
      networks:
        - little_farmer
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all
      volumes:
        - ./ollama:/root/.ollama:rw

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - little_farmer

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - little_farmer

networks:
  little_farmer:
    driver: bridge